### ISSUE TITLE
When attempting to add iOS platform, CocoaPods issue

### ISSUE THREAD

**Issue by libib** [Scandit/datacapture-cordova-samples#2]
When adding the iOS platform, I'm receiving the following warnings about  ```BCSimple```

Is this something I can ignore, or how otherwise how do I need to address this?

Using 12.0.0 (cordova-lib@12.0.1)
Cordova platform ios 7.0.1

```
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.scandit.barcodecapturesimplesample
	Name: BCSimple
iOS project created with cordova-ios@7.0.1
Installing "scandit-cordova-datacapture-barcode" for ios
Plugin dependency "scandit-cordova-datacapture-core@6.18.2" already fetched, using that version.
Installing "scandit-cordova-datacapture-core" for ios
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100   457    0   457    0     0    539      0 --:--:-- --:--:-- --:--:--   542
   100 16.4M  100 16.4M    0     0  8033k      0  0:00:02  0:00:02 --:--:-- 35.6M

[!] The `BCSimple [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `BCSimple [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.release.xcconfig'. This can lead to problems with the CocoaPods installation
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
   100   460    0   460    0     0    647      0 --:--:-- --:--:-- --:--:--   651
   100 8105k  100 8105k    0     0  5399k      0  0:00:01  0:00:01 --:--:-- 25.8M

[!] The `BCSimple [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `BCSimple [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.release.xcconfig'. This can lead to problems with the CocoaPods installation
Plugin "scandit-cordova-datacapture-core" already installed on ios. Making it top-level.

[!] The `BCSimple [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `BCSimple [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-BCSimple/Pods-BCSimple.release.xcconfig'. This can lead to problems with the CocoaPods installation


```

**Comment by libib** [comment]
Installed cocoapods via homebrew, and now receive the following error instead:

```
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.scandit.barcodecapturesimplesample
	Name: BCSimple
iOS project created with cordova-ios@7.0.1
Installing "scandit-cordova-datacapture-barcode" for ios
Plugin dependency "scandit-cordova-datacapture-core@6.18.2" already fetched, using that version.
Installing "scandit-cordova-datacapture-core" for ios
Failed to install 'scandit-cordova-datacapture-core': Error: Command failed with exit code 1: pod --version
/Library/Ruby/Site/2.6.0/rubygems.rb:264:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:283:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'
    at makeError (/Users/xxxxuser/Desktop/helloscandit/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/xxxxuser/Desktop/helloscandit/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Failed to install 'scandit-cordova-datacapture-barcode': Error: Command failed with exit code 1: pod --version
/Library/Ruby/Site/2.6.0/rubygems.rb:264:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:283:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'
    at makeError (/Users/xxxxuser/Desktop/helloscandit/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/xxxxuser/Desktop/helloscandit/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Command failed with exit code 1: pod --version
/Library/Ruby/Site/2.6.0/rubygems.rb:264:in `find_spec_for_exe': can't find gem cocoapods (>= 0.a) with executable pod (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:283:in `activate_bin_path'
	from /usr/local/bin/pod:23:in `<main>'

```

**Comment by ScanditSupport** [comment]
Hi @libib, 

it seems the CocoaPods were actually installed and your project should run. 

Can you please reach out to us directly and share a few snippets of your code on how you implemented Scandit? Ideally, please provide a full project so we can check its specific config. 

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
